export const AiAssistantLocalization = {
	buttonTexts: {
		rus: {
			context1: 'Ответь на основе контекста',
			context2: 'Подготовь саммари файла',
			context3: 'Создай новый документ',
			context4: 'Создай новый документ из шаблона',
			context5: 'Найди судебную практику для кейса',
			context6: 'Подготовь саммари веб-сайта',
			context7: 'Переведи документ на другой язык',
			context8: 'Проверь грамматику',
		},
		eng: {
			context1: 'Answer based on context',
			context2: 'Prepare a file summary',
			context3: 'Create a new document',
			context4: 'Create a new document from template',
			context5: 'Find case law for the case',
			context6: 'Prepare website summary',
			context7: 'Translate document to another language',
			context8: 'Check grammar',
		},
		esp: {
			context1: 'Responder basado en el contexto',
			context2: 'Preparar resumen del documento',
			context3: 'Crear un nuevo documento',
			context4: 'Crear un nuevo documento a partir de una plantilla',
			context5: 'Encontrar jurisprudencia para el caso',
			context6: 'Preparar resumen del sitio web',
			context7: 'Traducir documento a otro idioma',
			context8: 'Revisar gramática',
		},
		deu: {
			context1: 'Antwort basierend auf Kontext',
			context2: 'Dokumentzusammenfassung vorbereiten',
			context3: 'Neues Dokument erstellen',
			context4: 'Neues Dokument aus Vorlage erstellen',
			context5: 'Rechtsprechung für den Fall finden',
			context6: 'Webseiten-Zusammenfassung vorbereiten',
			context7: 'Dokument in eine andere Sprache übersetzen',
			context8: 'Grammatik überprüfen',
		},
		fra: {
			context1: 'Répondre en fonction du contexte',
			context2: 'Préparer le résumé du document',
			context3: 'Créer un nouveau document',
			context4: "Créer un nouveau document à partir d'un modèle",
			context5: 'Trouver la jurisprudence pour le cas',
			context6: 'Préparer le résumé du site web',
			context7: 'Traduire le document dans une autre langue',
			context8: 'Vérifier la grammaire',
		},
	},
	contextMessages: {
		rus: {
			context1: 'Ответь на вопрос на основе контекста: ',
			context2: 'Подготовь саммари документа',
			context3:
				'Создай новый Договор о неразглашении в свободной форме, подписывающие стороны — Иван Петров ivan@ivan.com и Николай Сидоров nick@nick.com',
			context4: 'Создай новый документ из шаблона',
			context5: 'Найди судебную практику для кейса: ',
			context6: 'Подготовь саммари веб-сайта по ссылке: ',
			context7: 'Переведи предоставленный документ на английский язык',
			context8: 'Проверь документ на грамматические ошибки',
		},
		eng: {
			context1: 'Answer based on context: ',
			context2: 'Prepare document summary',
			context3:
				'Create a new non-disclosure agreement, parties — John Black john@john.com and Nick Rush nick@nick.com',
			context4: 'Create a new document from template',
			context5: 'Find case law for the case: ',
			context6: 'Prepare website summary from the link: ',
			context7: 'Translate the provided document into English',
			context8: 'Check the document for grammatical errors',
		},
		esp: {
			context1: 'Responder basado en el contexto: ',
			context2: 'Preparar resumen del documento',
			context3:
				'Crear un nuevo acuerdo de confidencialidad, partes — Juan Negro juan@juan.com y Nick Rush nick@nick.com',
			context4: 'Crear un nuevo documento a partir de una plantilla',
			context5: 'Encontrar jurisprudencia para el caso: ',
			context6: 'Preparar resumen del sitio web desde el enlace: ',
			context7: 'Traducir el documento proporcionado al inglés',
			context8: 'Revisar el documento para errores gramaticales',
		},
		deu: {
			context1: 'Antwort basierend auf Kontext: ',
			context2: 'Dokumentzusammenfassung vorbereiten',
			context3:
				'Erstellen Sie eine neue Geheimhaltungsvereinbarung, Parteien — John Schwarz john@john.com und Nick Rush nick@nick.com',
			context4: 'Neues Dokument aus Vorlage erstellen',
			context5: 'Rechtsprechung für den Fall finden: ',
			context6: 'Webseiten-Zusammenfassung vom Link vorbereiten: ',
			context7: 'Übersetzen Sie das bereitgestellte Dokument ins Englische',
			context8: 'Überprüfen Sie das Dokument auf grammatikalische Fehler',
		},
		fra: {
			context1: 'Répondre en fonction du contexte: ',
			context2: 'Préparer le résumé du document',
			context3:
				'Créer un nouvel accord de non-divulgation, parties — John Noir john@john.com et Nick Rush nick@nick.com',
			context4: "Créer un nouveau document à partir d'un modèle",
			context5: 'Trouver la jurisprudence pour le cas: ',
			context6: 'Préparer le résumé du site web à partir du lien: ',
			context7: 'Traduire le document fourni en anglais',
			context8: 'Vérifier le document pour les erreurs grammaticales',
		},
	},
	uiText: {
		rus: {
			title: 'ИИ ассистент',
			subtitle: 'Создавай, модифицируй, проверяй с ИИ.',
			context: 'Выбрать контекст',
			attach: 'Прикрепить файлы',
			newChat: 'Новый чат',
			rag: 'Загрузить файлы для добавления собственного контекста',
			contracts: 'Открыть контракты',
			templates: 'Открыть шаблоны',
			language: 'Язык ассистента',
			openDoc: 'Открыть документ',
			infoStartWith: 'Начните с',
			infoContext: 'Добавьте контекст',
			messageAI: 'Напишите ассистенту...',
			infoContextHelp:
				'Контекст — это долговременная память вашего ассистента. Добавьте сюда ваши часто используемые данные, в этом случае ассистент сможет отвечать на их основе.',
		},
		eng: {
			title: 'AI assistant',
			subtitle: 'Create, modify, assess and more.',
			context: 'Select context',
			attach: 'Attach files',
			newChat: 'New chat',
			rag: 'Upload files to add your own context',
			contracts: 'Open contracts',
			templates: 'Open templates',
			language: 'Assistant language',
			openDoc: 'Open document',
			infoStartWith: 'Get started with',
			infoContext: 'Add context',
			messageAI: 'Message assistant...',
			infoContextHelp:
				"Context is your assistant's long-term memory. Add your frequently used data here, so the assistant can respond based on it.",
		},
		esp: {
			title: 'Asistente de IA',
			subtitle: 'Crear, modificar, evaluar y más.',
			context: 'Seleccionar contexto',
			attach: 'Adjuntar archivos',
			newChat: 'Nuevo chat',
			rag: 'Subir archivos para agregar tu propio contexto',
			contracts: 'Abrir contratos',
			templates: 'Abrir plantillas',
			language: 'Idioma del asistente',
			openDoc: 'Abrir documento',
			infoStartWith: 'Comienza con',
			infoContext: 'Añadir contexto',
			messageAI: 'Mensaje al asistente...',
			infoContextHelp:
				'El contexto es la memoria a largo plazo de tu asistente. Añade aquí tus datos de uso frecuente para que el asistente pueda responder en base a ellos.',
		},
		deu: {
			title: 'KI-Assistent',
			subtitle: 'Erstellen, ändern, bewerten und mehr.',
			context: 'Kontext auswählen',
			attach: 'Dateien anhängen',
			newChat: 'Neuer Chat',
			rag: 'Dateien hochladen, um eigenen Kontext hinzuzufügen',
			contracts: 'Verträge öffnen',
			templates: 'Vorlagen öffnen',
			language: 'Assistentensprache',
			openDoc: 'Dokument öffnen',
			infoStartWith: 'Beginnen Sie mit',
			infoContext: 'Kontext hinzufügen',
			messageAI: 'Nachricht an den Assistenten...',
			infoContextHelp:
				'Kontext ist das Langzeitgedächtnis Ihres Assistenten. Fügen Sie hier Ihre häufig verwendeten Daten hinzu, damit der Assistent darauf basierend antworten kann.',
		},
		fra: {
			title: 'Assistant IA',
			subtitle: 'Créer, modifier, évaluer et plus.',
			context: 'Sélectionner le contexte',
			attach: 'Joindre des fichiers',
			newChat: 'Nouveau chat',
			rag: 'Télécharger des fichiers pour ajouter votre propre contexte',
			contracts: 'Ouvrir les contrats',
			templates: 'Ouvrir les modèles',
			language: "Langue de l'assistant",
			openDoc: 'Ouvrir le document',
			infoStartWith: 'Commencez par',
			infoContext: 'Ajouter un contexte',
			messageAI: "Message à l'assistant...",
			infoContextHelp:
				"Le contexte est la mémoire à long terme de votre assistant. Ajoutez ici vos données fréquemment utilisées pour que l'assistant puisse répondre en fonction de celles-ci.",
		},
	},
};
